FROM node:22-bookworm-slim AS builder
WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-workspace.yaml tsconfig.json .npmrc ./
COPY packages/ ./packages/
COPY apps/ ./apps/
RUN pnpm install --frozen-lockfile=false
RUN pnpm -r run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
RUN npm install -g pnpm
COPY --from=builder /app ./
EXPOSE 4000
CMD ["pnpm", "--filter", "@discord-stremio/controller", "start"]
